# Use Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy current directory contents into the container
COPY . /app

# Run app.py when container starts
CMD ["python", "app.py"]
